Add highlight alert to be able to disable highlighting
liferay/liferay-learn pull request #156
Opened 2021-05-05 06:35 UTC by thektan

For #155 

I ended up styling it like an alert so it wouldn't mix with the navigation links. It'll also truncate on longer search terms. Let me know your thoughts.

![Screen Shot 2021-05-04 at 11 15 11 PM](https://user-images.githubusercontent.com/4496722/117103588-769cfc80-ad2f-11eb-9676-b77903dc0682.png)
Truncated:
![Screen Shot 2021-05-04 at 11 14 55 PM](https://user-images.githubusercontent.com/4496722/117103637-8fa5ad80-ad2f-11eb-94de-ba26e14c56a5.png)

---

Here's some other options I briefly explored:
The standard link seemed it could be confusing mixing JS actions and navigation links.
![Screen Shot 2021-05-04 at 2 36 14 PM](https://user-images.githubusercontent.com/4496722/117103746-bcf25b80-ad2f-11eb-9590-829abc31309a.png)
![Screen Shot 2021-05-04 at 1 23 27 PM](https://user-images.githubusercontent.com/4496722/117104668-68e87680-ad31-11eb-86e9-c2263b003a46.png)

Top page alert blocks more content and if the help center alert isn't closed yet, the stacked alerts would make the page look really busy. 
![Screen Shot 2021-05-04 at 8 53 12 PM](https://user-images.githubusercontent.com/4496722/117103853-f88d2580-ad2f-11eb-9315-ed82b1cc4e31.png)

cc @rdai10 @rbohl @lipusz @jrhoun

2021-05-05 07:32 UTC, lipusz commented
Thank you Kevin! 👏

2021-05-05 08:51 UTC, lipusz commented
https://issues.liferay.com/browse/LRDOCS-9397

2021-05-07 16:57 UTC, rdai10 requested changes
Thanks @thektan , very comprehensive! The code looks good, the only comment I have is styling the highlighting term as admonition. Admonition have special meaning in the flow of the text, mixing it in the nav dilutes its association. A suggestion might be to keep the background color and alert icon but remove the left border so the message still stands out but is different enough from an admonition. 

I also thought calling it "Search Matches" in your third screenshot may be more obvious to the average user, since learn's audience is broad. What do you think?

@jrhoun , any feedback?

2021-05-07 16:57 UTC, rdai10 commented on site/docs/_static/js/highlighting-alert.js
> + * https://github.com/sphinx-doc/sphinx/blob/9e1b4a8f1678e26670d34765e74edf3a3be3c62c/sphinx/themes/basic/static/doctools.js#L261-L267
Nice!

2021-05-10 16:52 UTC, jrhoun commented
@thektan - 

Thanks for the pull. RE:

> The code looks good, the only comment I have is styling the highlighting term as admonition. Admonition have special meaning in the flow of the text, mixing it in the nav dilutes its association. A suggestion might be to keep the background color and alert icon but remove the left border so the message still stands out but is different enough from an admonition.

I would agree with this if it is possible. As far as the terms shown, I think `Highlighting "xyz"` is fine to me.

2021-05-10 18:25 UTC, thektan commented
Updated! 
![Screen Shot 2021-05-10 at 10 57 30 AM](https://user-images.githubusercontent.com/4496722/117706596-58e1f400-b182-11eb-8598-6a5a324afe11.png)

2021-05-10 21:23 UTC, jrhoun commented
Merged. Thanks a lot!

2021-05-10 21:23 UTC, closed without merging